version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    env_file:
      - .env
  web:
    build:
      context: .
      args:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - BUILD_ENVIRONMENT=${BUILD_ENVIRONMENT}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app/drupal/modules:/var/www/drupal/web/modules/custom
      - ./app/drupal/themes:/var/www/drupal/web/modules/themes
      - ./app/drupal/profiles:/var/www/drupal/web/modules/profiles
      - ./app/drupal/config:/var/www/drupal/config
    links:
      - "db:mysql"
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${SSH_PORT}:22"
    tty: true
