version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    env_file:
      - default.env
  web:
    build:
      context: .
      args:
      - MYSQL_ROOT_PASSWORD=root
      - BUILD_ENVIRONMENT=dev
    env_file:
      - default.env
    depends_on:
      - db
    volumes:
      - ./app/drupal/modules:/var/www/drupal/web/modules/custom
      - ./app/drupal/themes:/var/www/drupal/web/modules/themes
      - ./app/drupal/profiles:/var/www/drupal/web/modules/profiles
      - ./app/drupal/config:/var/www/drupal/config
    links:
      - "db:mysql"
    ports:
      - '8888:80'
      - '8889:443'
      - '2222:22'
    tty: true
