require_mail: 0
require_mail_confirm: false
require_admin_confirm: false
register_role: ethereum_signup_user
register_link_text: 'Create new account using Ethereum'
register_terms_text: 'I want to create a Account on this website. By I signing this text (using Ethereum personal_sign) I agree to the following conditions.'
login_link_text: 'Log in with Ethereum'
login_welcome_text: "Welcome back!\r\nPlease sign to log-in today (#date).\r\n"
login_redirect: user
ui_visible_without_web3: 1
_core:
  default_config_hash: mm01GMRIGeoAy8RfMm0B6TTF54zKMngadWffdiv5C_U
